### ISSUE TITLE
Include a License file

### ISSUE THREAD

**Issue by vwbusguy** [SpriggsySpriggs/Pipecom#1]
This is a really cool thing that you've done.  Would you consider adding a LICENSE file (MIT, Apache, GPL, etc.), so that it can be used in other QBasic projects as well?

**Comment by SpriggsySpriggs** [comment]
The library is actually for QB64 but I'll look into including a license. I put this out there for anyone to use as they see fit

**Comment by vwbusguy** [comment]
Awesome - I was looking at it for use in QB64.

**Comment by vwbusguy** [comment]
If I might make a suggestion - the MIT license might be a good fit then as it at least includes the important "don't sue me if anything goes wrong" clause.

**Comment by vwbusguy** [comment]
I'm particularly interested in using it for this little project so I don't need to store shell output plaintext in a temp file.

https://github.com/vwbusguy/qbsh

**Comment by SpriggsySpriggs** [comment]
> I'm particularly interested in using it for this little project so I don't need to store shell output plaintext in a temp file.
> 
> https://github.com/vwbusguy/qbsh

Sure, go ahead! I'm glad someone is using my code.

**Comment by vwbusguy** [comment]
Many thanks!
